name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub Actions information
        run: |
          echo "👋 Hello, ${{ github.actor }}!"
          echo "📅 The workflow was triggered on ${{ github.event.head_commit.timestamp }}."
          echo "📝 The commit message is: ${{ github.event.head_commit.message }}."
      - name: Display job information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🧩 my name is  ${{ vars.MY_NAME }} operating system."
          echo "🛠️ My secrets is  ${{ secrets.MY_SECRET }} server hosted by GitHub!"
      - name: Display runner information
        run: |
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Display repository information
        run: |
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Display checkout information
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Display workflow information
        run: |
          echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Display job status
        run: |
          echo "🍏 This job's status is ${{ job.status }}."
