name: Deploy application on ec2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./testapp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/testapp:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-user: ${{ vars.EC2_USER }}
          server-ip: ${{ vars.EC2_SERVER_IP }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/testapp:latest
            docker stop testapp || true
            docker rm testapp || true
            docker run -d --name testapp -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/testapp:latest